version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_database
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    ports:
      - "5432:5432"
    networks:
      - my_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      - my_network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://my_database:5432/your_database
      SPRING_DATASOURCE_USERNAME: your_username
      SPRING_DATASOURCE_PASSWORD: your_password

networks:
  my_network:
    driver: bridge